import type { Experience, ExperienceCategory } from "@/types/database";

/**
 * Realistic demo catalog used two ways:
 *  1. By the in-memory MockExperienceProvider so the app is fully usable
 *     with zero external services configured.
 *  2. By scripts/seed-supabase.ts to populate a real Supabase database for
 *     a convincing demo/staging environment.
 */

export const CATEGORIES: { id: ExperienceCategory; label: string; icon: string; sortOrder: number }[] = [
  { id: "outdoor_adventure", label: "Outdoor & Adventure", icon: "mountain", sortOrder: 1 },
  { id: "food_drink", label: "Food & Drink", icon: "utensils", sortOrder: 2 },
  { id: "nightlife", label: "Nightlife", icon: "moon", sortOrder: 3 },
  { id: "arts_culture", label: "Arts & Culture", icon: "palette", sortOrder: 4 },
  { id: "wellness", label: "Wellness", icon: "heart", sortOrder: 5 },
  { id: "sports_fitness", label: "Sports & Fitness", icon: "dumbbell", sortOrder: 6 },
  { id: "music_entertainment", label: "Music & Entertainment", icon: "music", sortOrder: 7 },
  { id: "history_learning", label: "History & Learning", icon: "landmark", sortOrder: 8 },
  { id: "hidden_gem", label: "Hidden Gems", icon: "gem", sortOrder: 9 },
  { id: "day_trip", label: "Day Trips", icon: "car", sortOrder: 10 },
  { id: "travel", label: "Travel", icon: "plane", sortOrder: 11 },
  { id: "social", label: "Social", icon: "users", sortOrder: 12 },
];

type SeedExperience = Omit<Experience, "id" | "createdAt" | "updatedAt" | "reviewCount" | "rating"> & {
  rating: number;
  reviewCount: number;
};

const img = (seed: string, w = 1200, h = 800) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const EXPERIENCES: SeedExperience[] = [
  {
    slug: "sunset-kayaking-inner-harbor",
    title: "Sunset Kayaking on the Inner Harbor",
    description:
      "Paddle out as the sun drops behind Baltimore's skyline. A guided small-group kayak tour with a local outfitter, gear included. Calm water, golden light, and one of the best skyline views in the city — no experience necessary.",
    shortDescription: "Golden-hour kayaking with skyline views. No experience needed.",
    category: "outdoor_adventure",
    tags: ["outdoors", "adventure", "photography", "nature"],
    images: [img("photo-1502933691298-84fc14542831"), img("photo-1470252649378-9c29740c9fa8")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "913 S Ann St, Baltimore, MD 21231",
    latitude: 39.2818,
    longitude: -76.5926,
    priceLevel: "low",
    priceEstimate: 32,
    priceCurrency: "USD",
    durationMinutes: 90,
    indoorOutdoor: "outdoor",
    socialMode: "either",
    bestTimeOfDay: "evening",
    isHiddenGem: false,
    isFeatured: true,
    isPremium: false,
    externalBookingUrl: "https://www.baltimorewatertaxi.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Must be able to swim", "Minimum age 12"],
    availability: "Daily, weather permitting, Apr–Oct",
    rating: 4.8,
    reviewCount: 214,
  },
  {
    slug: "hidden-speakeasy-fells-point",
    title: "The Unmarked Door: Fells Point Speakeasy",
    description:
      "Behind an unmarked door off Thames Street sits one of the city's best-kept secrets — a Prohibition-styled cocktail bar with a bartender who builds drinks around your mood, not a menu. Low light, live jazz on Thursdays, and a strict no-phones-at-the-bar rule that somehow makes it better.",
    shortDescription: "An unmarked cocktail bar with mood-based drinks and live jazz.",
    category: "hidden_gem",
    tags: ["nightlife", "culture", "luxury"],
    images: [img("photo-1470337458703-46ad1756a187"), img("photo-1514933651103-005eec06c04b")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "Thames St, Baltimore, MD 21231",
    latitude: 39.2822,
    longitude: -76.5934,
    priceLevel: "medium",
    priceEstimate: 45,
    priceCurrency: "USD",
    durationMinutes: 120,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: true,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["21+"],
    availability: "Wed–Sat, 7pm–1am",
    rating: 4.9,
    reviewCount: 89,
  },
  {
    slug: "patapsco-valley-hike-photo",
    title: "Patapsco Valley Waterfall Hike",
    description:
      "A 4-mile loop through Patapsco Valley State Park past the Cascade Falls, an old railroad swinging bridge, and dense forest canopy — one of the best photography hikes within 30 minutes of the city. Moderate difficulty, dog-friendly.",
    shortDescription: "A scenic waterfall loop hike, 30 minutes from downtown.",
    category: "outdoor_adventure",
    tags: ["hiking", "nature", "photography", "outdoors"],
    images: [img("photo-1441974231531-c6227db76b6e"), img("photo-1678063412571-c09ec5f4a5cc")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "Patapsco Valley State Park, Elkridge, MD",
    latitude: 39.2298,
    longitude: -76.7355,
    priceLevel: "free",
    priceEstimate: 0,
    priceCurrency: "USD",
    durationMinutes: 150,
    indoorOutdoor: "outdoor",
    socialMode: "either",
    bestTimeOfDay: "morning",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Moderate fitness level"],
    availability: "Sunrise to sunset, year-round",
    rating: 4.7,
    reviewCount: 512,
  },
  {
    slug: "rooftop-yoga-flow",
    title: "Rooftop Sunrise Yoga Flow",
    description:
      "A vinyasa flow class on a downtown rooftop as the city wakes up. All levels welcome, mats provided, coffee after. One of the most peaceful ways to start a weekend.",
    shortDescription: "Sunrise vinyasa flow on a downtown rooftop, mats provided.",
    category: "wellness",
    tags: ["wellness", "fitness"],
    images: [img("photo-1544367567-0f2fcb009e0b"), img("photo-1506126613408-eca07ce68773")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "300 Light St, Baltimore, MD 21202",
    latitude: 39.2865,
    longitude: -76.6122,
    priceLevel: "low",
    priceEstimate: 20,
    priceCurrency: "USD",
    durationMinutes: 60,
    indoorOutdoor: "outdoor",
    socialMode: "group",
    bestTimeOfDay: "morning",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Sat & Sun, 7:30am",
    rating: 4.6,
    reviewCount: 143,
  },
  {
    slug: "night-market-food-crawl",
    title: "Night Market Street Food Crawl",
    description:
      "A guided walking tour through the city's best late-night food stalls — dumplings, tacos, wood-fired pizza, and a secret dessert stop. Small groups, local guide, six tastings included.",
    shortDescription: "Guided food crawl through six of the city's best late-night stalls.",
    category: "food_drink",
    tags: ["food", "nightlife", "culture"],
    images: [img("photo-1504674900247-0877df9cc836"), img("photo-1555939594-58d7cb561ad1")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "Lexington Market, Baltimore, MD 21201",
    latitude: 39.2904,
    longitude: -76.622,
    priceLevel: "medium",
    priceEstimate: 55,
    priceCurrency: "USD",
    durationMinutes: 150,
    indoorOutdoor: "outdoor",
    socialMode: "group",
    bestTimeOfDay: "evening",
    isHiddenGem: false,
    isFeatured: true,
    isPremium: true,
    externalBookingUrl: "https://www.viator.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Fri & Sat, 6:30pm",
    rating: 4.9,
    reviewCount: 331,
  },
  {
    slug: "indie-vinyl-listening-bar",
    title: "Vinyl Listening Bar",
    description:
      "A quiet, audiophile-grade listening bar where the only agenda is a curated record playing on a vintage sound system. No talking during side A. Natural wine and small plates.",
    shortDescription: "A hi-fi listening bar with curated vinyl and natural wine.",
    category: "music_entertainment",
    tags: ["music", "culture", "nightlife"],
    images: [img("photo-1483000805330-4eaf0a0d82da"), img("photo-1493225457124-a3eb161ffa5f")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "1500 Union Ave, Baltimore, MD 21211",
    latitude: 39.3168,
    longitude: -76.6284,
    priceLevel: "medium",
    priceEstimate: 30,
    priceCurrency: "USD",
    durationMinutes: 120,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["21+"],
    availability: "Thu–Sun, 8pm–midnight",
    rating: 4.8,
    reviewCount: 76,
  },
  {
    slug: "art-museum-after-hours",
    title: "Art Museum After Hours",
    description:
      "The city's contemporary art museum opens late once a month with a DJ in the atrium, cash bar, and free-flowing access to the current exhibitions. A completely different way to see the collection.",
    shortDescription: "Late-night museum access with a DJ and cash bar, once a month.",
    category: "arts_culture",
    tags: ["art", "culture", "music"],
    images: [img("photo-1518998053901-5348d3961a04"), img("photo-1531913764164-f85c52e6e654")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "10 Art Museum Dr, Baltimore, MD 21218",
    latitude: 39.3299,
    longitude: -76.6205,
    priceLevel: "low",
    priceEstimate: 15,
    priceCurrency: "USD",
    durationMinutes: 180,
    indoorOutdoor: "indoor",
    socialMode: "group",
    bestTimeOfDay: "evening",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Last Friday of the month, 7–11pm",
    rating: 4.5,
    reviewCount: 198,
  },
  {
    slug: "rock-climbing-intro-class",
    title: "Intro to Rock Climbing",
    description:
      "A beginner-friendly indoor climbing class covering harness safety, basic technique, and your first real routes. Small groups, all gear included, no experience or partner required.",
    shortDescription: "Beginner indoor climbing class — gear included, no partner needed.",
    category: "sports_fitness",
    tags: ["fitness", "adventure", "sports"],
    images: [img("photo-1520156557489-31c63271fcd4"), img("photo-1501450626433-39bbf117090e")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "5300 Erdman Ave, Baltimore, MD 21205",
    latitude: 39.3126,
    longitude: -76.5551,
    priceLevel: "medium",
    priceEstimate: 40,
    priceCurrency: "USD",
    durationMinutes: 90,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "afternoon",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: "https://www.movementgyms.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Closed-toe shoes recommended"],
    availability: "Daily, multiple time slots",
    rating: 4.7,
    reviewCount: 267,
  },
  {
    slug: "chesapeake-bay-day-trip",
    title: "Chesapeake Bay Lighthouse Day Trip",
    description:
      "A full-day excursion to the Chesapeake Bay's historic lighthouses, with a stop for fresh blue crab at a waterman's dock and a sunset sail back. Transportation included from downtown.",
    shortDescription: "Full-day lighthouse tour with fresh crab and a sunset sail.",
    category: "day_trip",
    tags: ["nature", "photography", "food", "history"],
    images: [img("photo-1567565890176-80ec662d62de"), img("photo-1621423733843-c8c96465323c")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "Departs from Baltimore Inner Harbor",
    latitude: 39.2847,
    longitude: -76.6076,
    priceLevel: "high",
    priceEstimate: 129,
    priceCurrency: "USD",
    durationMinutes: 480,
    indoorOutdoor: "outdoor",
    socialMode: "group",
    bestTimeOfDay: "morning",
    isHiddenGem: false,
    isFeatured: true,
    isPremium: true,
    externalBookingUrl: "https://www.cruisebaltimore.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Sat, seasonal (May–Sep)",
    rating: 4.9,
    reviewCount: 152,
  },
  {
    slug: "pottery-wheel-date-night",
    title: "Pottery Wheel Date Night",
    description:
      "A relaxed two-hour pottery class for two — clay, wheel time, glazing lesson, and wine included. You'll walk away with a piece to pick up two weeks later once it's fired.",
    shortDescription: "Two-hour wheel-throwing class for two, with wine.",
    category: "arts_culture",
    tags: ["art", "culture"],
    images: [img("photo-1565193566173-7a0ee3dbe261"), img("photo-1609881583302-61548332039c")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "16 W North Ave, Baltimore, MD 21201",
    latitude: 39.3092,
    longitude: -76.6172,
    priceLevel: "medium",
    priceEstimate: 85,
    priceCurrency: "USD",
    durationMinutes: 120,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "evening",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Thu–Sun evenings",
    rating: 4.8,
    reviewCount: 94,
  },
  {
    slug: "dc-monuments-bike-tour",
    title: "Monuments by Moonlight Bike Tour",
    description:
      "A guided evening bike tour through DC's monuments, lit up after dark with a fraction of the daytime crowds. Bikes and helmets included, easy pace, roughly 8 miles total.",
    shortDescription: "Evening bike tour through DC's lit-up monuments.",
    category: "outdoor_adventure",
    tags: ["outdoors", "history", "photography", "adventure"],
    images: [img("photo-1565571370459-5c78ebb358de"), img("photo-1617581629397-a72507c3de9e")],
    city: "Washington",
    region: "DC",
    country: "USA",
    address: "1100 Ohio Dr SW, Washington, DC 20024",
    latitude: 38.8894,
    longitude: -77.0353,
    priceLevel: "medium",
    priceEstimate: 48,
    priceCurrency: "USD",
    durationMinutes: 180,
    indoorOutdoor: "outdoor",
    socialMode: "group",
    bestTimeOfDay: "night",
    isHiddenGem: false,
    isFeatured: true,
    isPremium: false,
    externalBookingUrl: "https://www.bikeandroll.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Basic biking ability"],
    availability: "Daily, 7pm departure",
    rating: 4.9,
    reviewCount: 621,
  },
  {
    slug: "underground-comedy-basement",
    title: "The Basement Comedy Show",
    description:
      "A 60-seat basement comedy club that books touring comedians testing new material before big tours. Cash bar, intimate setting, and a two-drink minimum that's easy to hit.",
    shortDescription: "A 60-seat basement club with touring comedians testing new sets.",
    category: "nightlife",
    tags: ["nightlife", "culture"],
    images: [img("photo-1558970439-add78fc68990"), img("photo-1527224857830-43a7acc85260")],
    city: "Washington",
    region: "DC",
    country: "USA",
    address: "1215 U St NW, Washington, DC 20009",
    latitude: 38.9169,
    longitude: -77.0286,
    priceLevel: "low",
    priceEstimate: 25,
    priceCurrency: "USD",
    durationMinutes: 90,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["21+", "Two-drink minimum"],
    availability: "Thu–Sat, 8pm & 10pm shows",
    rating: 4.7,
    reviewCount: 118,
  },
  {
    slug: "central-park-picnic-photography",
    title: "Golden Hour Picnic & Photography Walk",
    description:
      "A curated picnic setup in Central Park at golden hour, followed by a guided photo walk to the park's most photogenic (and least crowded) corners. Blanket, food, and props included.",
    shortDescription: "A styled golden-hour picnic plus a guided photo walk.",
    category: "outdoor_adventure",
    tags: ["photography", "outdoors", "nature"],
    images: [img("photo-1519671845924-1fd18db430b8"), img("photo-1470753937643-efeb931202a9")],
    city: "New York",
    region: "NY",
    country: "USA",
    address: "Central Park, New York, NY 10024",
    latitude: 40.7812,
    longitude: -73.9665,
    priceLevel: "high",
    priceEstimate: 95,
    priceCurrency: "USD",
    durationMinutes: 120,
    indoorOutdoor: "outdoor",
    socialMode: "either",
    bestTimeOfDay: "evening",
    isHiddenGem: false,
    isFeatured: true,
    isPremium: true,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Daily, weather permitting",
    rating: 4.8,
    reviewCount: 287,
  },
  {
    slug: "brooklyn-warehouse-rave",
    title: "Warehouse Basement Rave",
    description:
      "A DIY warehouse party in Bushwick with a rotating cast of underground DJs, a proper sound system, and zero bottle service energy. Doors at 11, gets going after 1.",
    shortDescription: "Underground warehouse party in Bushwick, proper sound system.",
    category: "nightlife",
    tags: ["nightlife", "music"],
    images: [img("photo-1470225620780-dba8ba36b745"), img("photo-1578736641330-3155e606cd40")],
    city: "New York",
    region: "NY",
    country: "USA",
    address: "Bushwick, Brooklyn, NY 11237",
    latitude: 40.6942,
    longitude: -73.9219,
    priceLevel: "medium",
    priceEstimate: 30,
    priceCurrency: "USD",
    durationMinutes: 300,
    indoorOutdoor: "indoor",
    socialMode: "group",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["21+"],
    availability: "Select Saturdays, check listings",
    rating: 4.6,
    reviewCount: 402,
  },
  {
    slug: "tokyo-izakaya-crawl",
    title: "Shinjuku Izakaya Crawl",
    description:
      "A guided crawl through three tiny izakayas tucked into Golden Gai's alleyways — the kind of places that seat six people and don't have English menus. Local host, all food and drink included.",
    shortDescription: "A local-guided crawl through tiny Golden Gai izakayas.",
    category: "food_drink",
    tags: ["food", "nightlife", "culture"],
    images: [img("photo-1554797589-7241bb691973"), img("photo-1503899036084-c55cdd92da26")],
    city: "Tokyo",
    region: null,
    country: "Japan",
    address: "Golden Gai, Shinjuku, Tokyo",
    latitude: 35.6938,
    longitude: 139.7034,
    priceLevel: "high",
    priceEstimate: 110,
    priceCurrency: "USD",
    durationMinutes: 180,
    indoorOutdoor: "indoor",
    socialMode: "group",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: true,
    isPremium: true,
    externalBookingUrl: "https://www.viator.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["21+"],
    availability: "Tue–Sun, 7pm",
    rating: 4.9,
    reviewCount: 356,
  },
  {
    slug: "tokyo-teamlab-digital-art",
    title: "teamLab Digital Art Immersion",
    description:
      "A borderless digital art museum where every room reacts to your movement — flowers that bloom underfoot, waterfalls of light, mirrored infinity rooms. Book the early morning slot to beat crowds.",
    shortDescription: "An immersive, movement-reactive digital art museum.",
    category: "arts_culture",
    tags: ["art", "technology", "culture", "photography"],
    images: [img("photo-1785637981940-0ec1cfefed10"), img("photo-1786521641447-6c6b56737e92")],
    city: "Tokyo",
    region: null,
    country: "Japan",
    address: "Azabudai Hills, Tokyo",
    latitude: 35.6627,
    longitude: 139.7431,
    priceLevel: "medium",
    priceEstimate: 32,
    priceCurrency: "USD",
    durationMinutes: 150,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "morning",
    isHiddenGem: false,
    isFeatured: true,
    isPremium: false,
    externalBookingUrl: "https://www.teamlab.art",
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Daily, timed entry",
    rating: 4.9,
    reviewCount: 891,
  },
  {
    slug: "tokyo-mt-takao-hike",
    title: "Mt. Takao Sunrise Hike",
    description:
      "An early hike up Mt. Takao before the cable cars start running, with sweeping views of Tokyo and, on clear days, Mt. Fuji itself. Finish with fresh soba at a trailside shop.",
    shortDescription: "Sunrise hike with Mt. Fuji views and trailside soba.",
    category: "outdoor_adventure",
    tags: ["hiking", "nature", "photography", "outdoors"],
    images: [img("photo-1613144488732-19df6d7e8656"), img("photo-1712035739023-d931a012d267")],
    city: "Tokyo",
    region: null,
    country: "Japan",
    address: "Mt. Takao, Hachioji, Tokyo",
    latitude: 35.6253,
    longitude: 139.2431,
    priceLevel: "free",
    priceEstimate: 0,
    priceCurrency: "USD",
    durationMinutes: 240,
    indoorOutdoor: "outdoor",
    socialMode: "either",
    bestTimeOfDay: "morning",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Moderate fitness level"],
    availability: "Daily, sunrise start recommended",
    rating: 4.8,
    reviewCount: 445,
  },
  {
    slug: "farm-to-table-supper-club",
    title: "Farm-to-Table Supper Club",
    description:
      "A monthly, communal-table dinner series hosted in a working farm's barn — five courses, all sourced within 20 miles, family-style. Strangers sit together on purpose.",
    shortDescription: "A communal five-course barn dinner, sourced within 20 miles.",
    category: "food_drink",
    tags: ["food", "culture", "learning"],
    images: [img("photo-1414235077428-338989a2e8c0"), img("photo-1787298537604-5ecdd342bd72")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "Glen Arm, MD 21057",
    latitude: 39.4737,
    longitude: -76.5044,
    priceLevel: "high",
    priceEstimate: 85,
    priceCurrency: "USD",
    durationMinutes: 180,
    indoorOutdoor: "indoor",
    socialMode: "group",
    bestTimeOfDay: "evening",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: true,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "First Saturday monthly",
    rating: 5.0,
    reviewCount: 61,
  },
  {
    slug: "escape-room-heist",
    title: "The Vault Heist Escape Room",
    description:
      "A 60-minute high-production escape room built like a bank heist — lasers, a real safe, and an actor who occasionally shows up to mess with your plan. One of the highest-rated rooms in the city.",
    shortDescription: "A high-production heist-themed escape room, 60 minutes.",
    category: "social",
    tags: ["adventure", "entrepreneurship", "technology"],
    images: [img("photo-1582139329536-e7284fece509"), img("photo-1592744254966-58c65cfd2e69")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "34 Market Pl, Baltimore, MD 21202",
    latitude: 39.2865,
    longitude: -76.6088,
    priceLevel: "medium",
    priceEstimate: 38,
    priceCurrency: "USD",
    durationMinutes: 60,
    indoorOutdoor: "indoor",
    socialMode: "group",
    bestTimeOfDay: "any",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: "https://www.escaperoom.com",
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["2-8 people per group"],
    availability: "Daily, hourly slots",
    rating: 4.7,
    reviewCount: 503,
  },
  {
    slug: "stargazing-observatory-night",
    title: "Observatory Stargazing Night",
    description:
      "A public astronomy night at a local university observatory — telescope viewing, a short talk from a grad student, and (on clear nights) a good look at Saturn's rings.",
    shortDescription: "Public telescope night with a short astronomy talk.",
    category: "history_learning",
    tags: ["learning", "nature", "photography"],
    images: [img("photo-1419242902214-272b3f66ee7a"), img("photo-1444703686981-a3abbc4d4fe3")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "3400 N Charles St, Baltimore, MD 21218",
    latitude: 39.3299,
    longitude: -76.6205,
    priceLevel: "free",
    priceEstimate: 0,
    priceCurrency: "USD",
    durationMinutes: 90,
    indoorOutdoor: "outdoor",
    socialMode: "either",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Weather dependent"],
    availability: "First Friday monthly, clear skies only",
    rating: 4.6,
    reviewCount: 72,
  },
  {
    slug: "startup-founders-mixer",
    title: "Founders & Builders Mixer",
    description:
      "A low-key monthly mixer for early-stage founders, indie hackers, and people building things on the side. Lightning demos, good coffee, better conversation.",
    shortDescription: "A monthly mixer for founders and indie hackers.",
    category: "social",
    tags: ["entrepreneurship", "technology", "learning"],
    images: [img("photo-1515187029135-18ee286d815b"), img("photo-1552664730-d307ca884978")],
    city: "Washington",
    region: "DC",
    country: "USA",
    address: "1100 15th St NW, Washington, DC 20005",
    latitude: 38.9038,
    longitude: -77.0342,
    priceLevel: "free",
    priceEstimate: 0,
    priceCurrency: "USD",
    durationMinutes: 120,
    indoorOutdoor: "indoor",
    socialMode: "group",
    bestTimeOfDay: "evening",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Third Thursday monthly",
    rating: 4.5,
    reviewCount: 58,
  },
  {
    slug: "luxury-spa-day-retreat",
    title: "Full-Day Spa Retreat",
    description:
      "A full day at a downtown wellness spa — soaking pools, sauna circuit, 90-minute massage, and a quiet lounge with tea service. The kind of reset that's worth planning a whole day around.",
    shortDescription: "A full day of soaking pools, sauna, and a 90-minute massage.",
    category: "wellness",
    tags: ["wellness", "luxury"],
    images: [img("photo-1540555700478-4be289fbecef"), img("photo-1712659604528-b179a3634560")],
    city: "New York",
    region: "NY",
    country: "USA",
    address: "10 Columbus Cir, New York, NY 10019",
    latitude: 40.7681,
    longitude: -73.9819,
    priceLevel: "luxury",
    priceEstimate: 275,
    priceCurrency: "USD",
    durationMinutes: 300,
    indoorOutdoor: "indoor",
    socialMode: "solo",
    bestTimeOfDay: "morning",
    isHiddenGem: false,
    isFeatured: false,
    isPremium: true,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["Reservation required"],
    availability: "Daily, by appointment",
    rating: 4.9,
    reviewCount: 234,
  },
  {
    slug: "graffiti-alley-street-art-tour",
    title: "Graffiti Alley Street Art Tour",
    description:
      "A self-guided walking route through the city's legal graffiti district, with a companion audio guide covering the artists and the history behind the biggest murals. Great for photography.",
    shortDescription: "A self-guided street art walk with an audio guide.",
    category: "arts_culture",
    tags: ["art", "photography", "culture"],
    images: [img("photo-1530406831759-15c5c0cbce8b"), img("photo-1604716053460-3f66248bf8de")],
    city: "Baltimore",
    region: "MD",
    country: "USA",
    address: "N Howard St, Baltimore, MD 21201",
    latitude: 39.2989,
    longitude: -76.6177,
    priceLevel: "free",
    priceEstimate: 0,
    priceCurrency: "USD",
    durationMinutes: 60,
    indoorOutdoor: "outdoor",
    socialMode: "either",
    bestTimeOfDay: "afternoon",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: [],
    availability: "Always open",
    rating: 4.4,
    reviewCount: 87,
  },
  {
    slug: "live-jazz-basement-club",
    title: "Basement Jazz Club",
    description:
      "A no-frills basement jazz club that's been running the same Tuesday night jam session for 20 years. House trio, open sign-up for musicians, and the best $10 cover in the city.",
    shortDescription: "A 20-year-running Tuesday night jazz jam session.",
    category: "music_entertainment",
    tags: ["music", "culture", "nightlife"],
    images: [img("photo-1415201364774-f6f0bb35f28f"), img("photo-1415886541506-6efc5e4b1786")],
    city: "Washington",
    region: "DC",
    country: "USA",
    address: "2003 11th St NW, Washington, DC 20001",
    latitude: 38.9186,
    longitude: -77.0273,
    priceLevel: "low",
    priceEstimate: 10,
    priceCurrency: "USD",
    durationMinutes: 150,
    indoorOutdoor: "indoor",
    socialMode: "either",
    bestTimeOfDay: "night",
    isHiddenGem: true,
    isFeatured: false,
    isPremium: false,
    externalBookingUrl: null,
    sourceProvider: "mock",
    sourceId: null,
    requirements: ["21+"],
    availability: "Every Tuesday, 9pm",
    rating: 4.8,
    reviewCount: 165,
  },
];

export const DESTINATIONS = [
  {
    slug: "tokyo-japan",
    city: "Tokyo",
    country: "Japan",
    description:
      "A city where 800-year-old temples sit blocks from neon megascreens. Endless neighborhoods, each with its own personality — come hungry and comfortable walking.",
    coverImage: img("photo-1540959733332-eab4deabeeaf", 1600, 900),
    latitude: 35.6762,
    longitude: 139.6503,
    bestMonths: ["March", "April", "October", "November"],
  },
  {
    slug: "new-york-usa",
    city: "New York",
    country: "USA",
    description: "The city that runs on momentum. World-class everything, all night, every night.",
    coverImage: img("photo-1496442226666-8d4d0e62e6e9", 1600, 900),
    latitude: 40.7128,
    longitude: -74.006,
    bestMonths: ["April", "May", "September", "October"],
  },
  {
    slug: "washington-dc-usa",
    city: "Washington",
    country: "USA",
    description: "Free-entry world-class museums, a serious food scene, and monuments that hit different at night.",
    coverImage: img("photo-1617581629397-a72507c3de9e", 1600, 900),
    latitude: 38.9072,
    longitude: -77.0369,
    bestMonths: ["April", "May", "September", "October"],
  },
];
